parameters:
    biz_config:
        debug: "%kernel.debug%"
        db.options:
            dbname: "%database_name%"
            user: "%database_user%"
            password: "%database_password%"
            host: "%database_host%"
            port: "%database_port%"
            driver: pdo_mysql
            charset: UTF8
        cache_directory: "%kernel.root_dir%/../var/cache"
        tmp_directory: "%kernel.root_dir%/../var/tmp"
        log_directory: "%kernel.root_dir%/../var/logs"

services:
    biz:
        class: Codeages\Biz\Framework\Context\Biz
        arguments: ["%biz_config%"]