parameters:
    biz_config:
        debug: "%kernel.debug%"
        db.options: "%biz_db_options%"
        root_directory: "%kernel.root_dir%/../"
        cache_directory: "%kernel.cache_dir%"
        log_directory: "%kernel.logs_dir%"
        kernel.root_dir: "%kernel.root_dir%"
        plugin.directory: "%kernel.root_dir%/../plugins"
        theme.directory: "%kernel.root_dir%/../web/themes"
        topxia.upload.public_url_path: "%topxia.upload.public_url_path%"
        topxia.web_themes_url_path: "%topxia.web_themes_url_path%"
        front_end.web_static_dist_url_path: "%front_end.web_static_dist_url_path%"
        topxia.web_assets_url_path: "%topxia.web_assets_url_path%"
        topxia.web_bundles_url_path: "%topxia.web_bundles_url_path%"
        topxia.disk.local_directory: "%topxia.disk.local_directory%"
        topxia.disk.backup_dir: "%topxia.disk.backup_dir%"
        topxia.disk.update_dir: "%topxia.disk.update_dir%"
        topxia.upload.public_directory: "%topxia.upload.public_directory%"
        topxia.upload.private_directory: "%topxia.upload.private_directory%"
        plugin.config_file: "%kernel.root_dir%/config/plugin_installed.php"
        service_proxy_enabled: "%service_proxy_enabled%"
        run_dir: "%kernel.root_dir%/run"
        cache_dir: "%kernel.cache_dir%"

    biz_db_options:
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        host: "%database_host%"
        port: "%database_port%"
        driver: pdo_mysql
        charset: UTF8



services:
    biz:
        class: Codeages\Biz\Framework\Context\Biz
        arguments: ["%biz_config%"]
        public: true