imports:
    - { resource: parameters_default.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    # esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: 3.7.4
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:     session.handler.pdo
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    paths:
        "%kernel.root_dir%/../web/customize": customize
        "%kernel.root_dir%/../src/Topxia/WebBundle/Resources/views": topxiaweb
    globals:
        disabled_features: %disabled_features%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    #spool:     { type: memory }

#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false

parameters:
    session.handler.pdo.options:
        db_table:    session2
        db_id_col:   session_id
        db_data_col: session_value
        db_time_col: session_time

    topxia.disk.local_directory: "%kernel.root_dir%/data/udisk"
    topxia.disk.cloud_video_fop: "avthumb/mp4/r/30/vb/512k/vcodec/libx264/ar/22050/ab/64k/acodec/libfaac"
    topxia.disk.upgrade_dir: "%kernel.root_dir%/data/upgrade"
    topxia.disk.update_dir: "%kernel.root_dir%/data/upgrade"
    topxia.disk.backup_dir: "%kernel.root_dir%/data/backup"
    topxia.upload.public_directory: "%kernel.root_dir%/../web/files"
    topxia.upload.public_url_path: "/files"
    topxia.upload.private_directory: "%kernel.root_dir%/data/private_files"

services:
    session.handler.pdo.connection:
        class: PDO
        calls:
            - [setAttribute, [3, 2]]

        arguments:
            dsn:      "mysql:host=%database_host%;dbname=%database_name%"
            user:     %database_user%
            password: %database_password%

    session.handler.pdo:
        class:     Topxia\WebBundle\Handler\UserPdoSessionHandler
        arguments: [@session.handler.pdo.connection, %session.handler.pdo.options%, @security.context]

    kernel.listener.ajax_exception_listener:
        class: Topxia\WebBundle\Listener\AjaxExceptionListener
        arguments:    [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority:255 }

    kernel.listener.kernel_request_listener:
        class: Topxia\WebBundle\Listener\KernelRequestListener
        arguments:    [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority:255 }

    topxia.twig.web_extension:
        class: Topxia\WebBundle\Twig\Extension\WebExtension
        arguments:    [@service_container]
        tags:
            - { name: twig.extension }

    topxia.twig.html_extension:
        class: Topxia\WebBundle\Twig\Extension\HtmlExtension
        tags:
            - { name: twig.extension }

    topxia.twig.data_extension:
        class: Topxia\WebBundle\Twig\Extension\DataExtension
        tags:
            - { name: twig.extension }




    kernel.listener.user_login_token_listener:
        class: Topxia\WebBundle\Listener\UserLoginTokenListener
        arguments:    [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onGetUserLoginListener}
