imports:
    - { resource: biz.yml }
    - { resource: parameters_default.yml }
    - { resource: parameters_version.yml }
    - { resource: parameters_service.yml, ignore_errors: true }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.xml }
    - { resource: service_listener.yml }
    - { resource: session_redis.yml, ignore_errors: true }
    - { resource: sentry.yml, ignore_errors: true }
    - { resource: theme_jianmo_parameters.yml }
    - { resource: "@CustomBundle/Resources/config/services.yml" }

framework:
    # esi:             ~
    translator:      { fallback: "%locale%", logging: false }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id:  "%session.service_id%"
    fragments:       ~
    http_method_override: true
    assets:
        version: '%app_version%'

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../web/customize": customize
        "%kernel.root_dir%/../src/Topxia/WebBundle/Resources/views": topxiaweb
        "%kernel.root_dir%/../web/themes": theme
        "%kernel.root_dir%/../plugins": plugins
        "%kernel.root_dir%/../" : root

# Swiftmailer Configuration
# swiftmailer:
#     transport: %mailer_transport%
#     host:      %mailer_host%
#     username:  %mailer_user%
#     password:  %mailer_password%
    #spool:     { type: memory }

#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false

parameters:
    session.handler.pdo.options:
         db_table:    sessions
         db_id_col:   sess_id
         db_data_col: sess_data
         db_time_col: sess_time
         db_lifetime_col: sess_lifetime
         db_user_id_col: sess_user_id

    topxia.disk.local_directory: "%kernel.root_dir%/data/udisk"
    topxia.disk.upgrade_dir: "%kernel.root_dir%/data/upgrade"
    topxia.disk.update_dir: "%kernel.root_dir%/data/upgrade"
    topxia.disk.backup_dir: "%kernel.root_dir%/data/backup"
    topxia.upload.public_directory: "%kernel.root_dir%/../web/files"
    topxia.upload.public_url_path: "/files"
    topxia.upload.private_directory: "%kernel.root_dir%/data/private_files"
    permission.path_regular_expression: ['/^\/admin/']
    router.options.matcher_dumper_class: AppBundle\SfExtend\PhpMatcherDumper
    security.authentication.provider.dao.class: AppBundle\Handler\AuthenticationProvider

services:

    assets.path_package:
        class: AppBundle\Twig\Asset\PathPackage
        arguments: ["", "", "@assets.context"]

    session.handler.pdo.connection:
        class: PDO
        calls:
            - [setAttribute, [3, 2]]

        arguments:
            dsn:      "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            user:     "%database_user%"
            password: "%database_password%"

    session.handler.pdo:
        class:     AppBundle\Handler\UserPdoSessionHandler
        arguments: ['@session.handler.pdo.connection', '%session.handler.pdo.options%', '@security.token_storage']

    session.handler.redis:
        class:     AppBundle\Handler\RedisSessionHandler
        arguments: ['@session.handler.redis.factory', '@security.token_storage']

    session.handler.redis.factory:
        class:     AppBundle\Handler\RedisSessionFactory
        arguments: ['@service_container']

    topxia.twig.file_cache:
        class: Biz\Common\FilesystemCache
        arguments:    ['@service_container']

    topxia.twig.cache_provider:
        class: Asm89\Twig\CacheExtension\CacheProvider\DoctrineCacheAdapter
        arguments:    ['@topxia.twig.file_cache']

    topxia.twig.cache_strategy:
        class: Biz\Common\LifetimeCacheStrategy
        arguments:    ['@biz', '@topxia.twig.cache_provider']

    topxia.twig.cache_extension:
        class: Asm89\Twig\CacheExtension\Extension
        arguments:    ['@topxia.twig.cache_strategy']
        tags:
            - { name: twig.extension }

    ### permission
    permission.admin_voter:
        class: AppBundle\SfExtend\AdminVoter
        tags:
            - { name: security.voter }
        public: false

    permission.twig.permission_extension:
        class: AppBundle\Twig\PermissionExtension
        arguments:    ['@service_container']
        tags:
            - { name: twig.extension }

    routing.loader.yml:
        class: AppBundle\SfExtend\YamlFileLoader
        arguments: ['@file_locator']
        tags:
            - {name: routing.loader}
