__web:
    resource: "@TopxiaWebBundle/Resources/config/routing.yml"

topxia_admin:
    resource: "@TopxiaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

# Internal routing configuration to handle ESI
# _internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal