__web:
    resource: "@TopxiaWebBundle/Resources/config/routing.yml"

topxia_admin:
    resource: "@TopxiaAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

_plugins:
    resource: routing_plugins.yml

custom_web:
    resource: "@CustomWebBundle/Resources/config/routing.yml"
    prefix:   /

custom_admin:
    resource: "@CustomAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

# Internal routing configuration to handle ESI
# _internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal