services:
    topxia.user_provider:
        class: Biz\User\UserProvider
        arguments:    ['@service_container']

    topxia.authentication.failure_handler:
        class: AppBundle\Handler\AuthenticationFailureHandler
        parent: security.authentication.failure_handler

    topxia.authentication.success_handler:
        class: AppBundle\Handler\AuthenticationSuccessHandler
        parent: security.authentication.success_handler
    topxia.logout.success_handler:
        class: AppBundle\Handler\LogoutSuccessHandler
        parent: security.logout.success_handler

    user.login_listener:
        class: AppBundle\Handler\LoginSuccessHandler
        arguments: ['@security.authorization_checker']
        tags: [{ name: kernel.event_listener, event: security.interactive_login }]

    user.login_generate_notification_handler:
        class: AppBundle\Handler\GenerateNotificationHandler
        arguments: ['@service_container']
        tags: [{ name: kernel.event_listener, event: security.interactive_login }]

security:
    encoders:
        Biz\User\CurrentUser: sha256

    providers:
        custom_provider:
            id: topxia.user_provider

    role_hierarchy: "%role_hierarchy%"

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        disabled:
            pattern: ^/(anon|callback|api)/
            security: false

        main:
            pattern:    /.*
            form_login:
                login_path: login
                check_path: login_check
                use_referer: true
                failure_handler: topxia.authentication.failure_handler
                success_handler: topxia.authentication.success_handler
            remember_me:
                secret: "%secret%"
                lifetime: 31536000
                path: /
                domain: "%cookie_domain%"
            logout:
                path:   logout
                success_handler: topxia.logout.success_handler
            anonymous:  true
    access_control:
        - { path: ^/crontab, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/task, role: ROLE_USER }
        - { path: ^/my, role: ROLE_USER }
        - { path: ^/settings, role: ROLE_USER }
        - { path: ^/cashier, role: ROLE_USER }
        - { path: ^/order, role: ROLE_USER }
        - { path: ^/message, role: ROLE_USER }
        - { path: ^/classroom/\d+/manage/, role: ROLE_USER }
        - { path: ^/admin/course, role: ROLE_BACKEND }
        - { path: ^/admin/user, role: ROLE_BACKEND }
        - { path: ^/admin/app, role: ROLE_BACKEND }
        - { path: ^/admin/setting, role: ROLE_BACKEND }
        - { path: ^/admin/logs, role: ROLE_BACKEND }
        - { path: ^/admin/upgrade, role: ROLE_BACKEND }
        - { path: ^/admin/optimize, role: ROLE_BACKEND }
        - { path: ^/admin, role: ROLE_BACKEND }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
