services:
    topxia.user_provider:
        class: Topxia\Service\User\UserProvider
        arguments:    [@service_container]

    security.access.blacklist_voter:
        class:      Topxia\WebBundle\Security\Voter\ClientIpVoter
        arguments:  [@service_container]
        public:     false
        tags:
            - { name: security.voter }

    topxia.authentication.failure_handler:
        class: Topxia\WebBundle\Handler\AuthenticationFailureHandler
        parent: security.authentication.failure_handler
        calls:
            - [setTranslator, [@translator]]

    topxia.authentication.success_handler:
        class: Topxia\WebBundle\Handler\AuthenticationSuccessHandler
        parent: security.authentication.success_handler

security:
    encoders:
        Topxia\Service\User\CurrentUser: sha256

    providers:
        custom_provider:
            id: topxia.user_provider

    role_hierarchy:
        ROLE_TEACHER:     ROLE_USER
        ROLE_ADMIN:       ROLE_TEACHER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        main:
            pattern:    /.*
            form_login:
                login_path: login
                check_path: login_check
                use_referer: true
                failure_handler: topxia.authentication.failure_handler
                success_handler: topxia.authentication.success_handler
            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~
            logout:
                path:   logout
                target: /
            anonymous:  true
    access_control:
        - { path: ^/task, role: ROLE_USER }
        - { path: ^/me, role: ROLE_USER }
        - { path: ^/settings, role: ROLE_USER }
        # - { path: ^/note, role: ROLE_USER }
        - { path: ^/message, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
