parameters:

  theme_jianmo_name: "简墨"

  theme_jianmo_default:
    maincolor: default
    navigationcolor: default
    blocks:
      left:
        - title: ""
          count: "12"
          orderBy: "latest"
          background: ""
          categoryId: 0
          code: course-grid-with-condition-index
          categoryCount: "4"
          defaultTitle: "网校课程"
          subTitle: ""
          defaultSubTitle: "精选网校课程，满足你的学习兴趣。"
          id: "latestCourse"
        - title: ""
          count: "4"
          categoryId: ""
          code: "live-course"
          defaultTitle: "近期直播"
          subTitle: ""
          background: ""
          defaultSubTitle: "实时跟踪直播课程，避免课程遗漏。"
          id: "RecentLiveCourses"
        - title: ""
          count: ""
          code: "middle-banner"
          defaultTitle: "首页中部.横幅"
          id: "middle-banner"
        - title: ""
          count: "4"
          code: "recommend-classroom"
          defaultTitle: "推荐班级"
          subTitle: ""
          background: ""
          defaultSubTitle: "班级化学习体系，给你更多的课程相关服务。"
          id: "RecommendClassrooms"
        - title: ""
          count: "6"
          code: "groups"
          defaultTitle: "动态"
          subTitle: ""
          background: ""
          defaultSubTitle: "参与小组，结交更多同学，关注课程动态。"
          select1: "checked"
          select2: "checked"
          select3: ""
          select4: ""
          id: "hotGroups"
        - title: ""
          count: "4"
          categoryId: ""
          code: "recommend-teacher"
          defaultTitle: "推荐教师"
          subTitle: ""
          background: ""
          defaultSubTitle: "名师汇集，保证教学质量与学习效果。"
          id: "RecommendTeachers"
        - title: ""
          count: ""
          code: "friend-link"
          defaultTitle: "友情链接"
          id: "friendLink"
        - title: ""
          count: ""
          code: "footer-link"
          defaultTitle: "底部链接"
          id: "footerLink"
    bottom: simple

  theme_jianmo_all:
    maincolor: default
    navigationcolor: default
    blocks:
      left:
        - title: ""
          count: "12"
          orderBy: "latest"
          background: ""
          categoryId: 0
          code: course-grid-with-condition-index
          categoryCount: "4"
          defaultTitle: "网校课程"
          subTitle: ""
          defaultSubTitle: "精选网校课程，满足你的学习兴趣。"
          id: "latestCourse"
        - title: ""
          count: "12"
          orderBy: "latest"
          background: ""
          categoryId: 0
          code: open-course
          categoryCount: "4"
          defaultTitle: "公开课"
          subTitle: ""
          defaultSubTitle: "公开课。"
          id: "latestOpenCourse"
        - title: ""
          count: "4"
          categoryId: ""
          code: "live-course"
          defaultTitle: "近期直播"
          subTitle: ""
          background: ""
          defaultSubTitle: "实时跟踪直播课程，避免课程遗漏。"
          id: "RecentLiveCourses"
        - title: ""
          count: ""
          code: "middle-banner"
          defaultTitle: "首页中部.横幅"
          id: "middle-banner"
        - title: ""
          count: "4"
          code: "recommend-classroom"
          defaultTitle: "推荐班级"
          subTitle: ""
          background: ""
          defaultSubTitle: "班级化学习体系，给你更多的课程相关服务。"
          id: "RecommendClassrooms"
        - title: ""
          count: ""
          code: "advertisement-banner"
          defaultTitle: "中部广告"
          id: "advertisement-banner"
        - title: ""
          count: "6"
          code: "groups"
          defaultTitle: "动态"
          subTitle: ""
          background: ""
          defaultSubTitle: "参与小组，结交更多同学，关注课程动态。"
          select1: "checked"
          select2: "checked"
          select3: ""
          select4: ""
          id: "hotGroups"
        - title: ""
          count: "4"
          categoryId: ""
          code: "recommend-teacher"
          defaultTitle: "推荐教师"
          subTitle: ""
          background: ""
          defaultSubTitle: "名师汇集，保证教学质量与学习效果。"
          id: "RecommendTeachers"
        - title: ""
          count: ""
          code: "friend-link"
          defaultTitle: "友情链接"
          id: "friendLink"
        - title: ""
          count: ""
          code: "footer-link"
          defaultTitle: "底部链接"
          id: "footerLink"
    bottom: simple
services:
#    topxia_admin.example:
#        class: %topxia_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
