course_create:
    pattern:  /custom/course/create
    defaults: { _controller: CustomWebBundle:Course:create }

course_next_round:
    pattern: /course/{id}/nextRound
    defaults: { _controller: CustomWebBundle:Course:nextRound }

course_rounding:
    pattern: /course/{id}/rounding
    defaults: { _controller: CustomWebBundle:Course:rounding }

course_explore:
    pattern:  /mooc/course/explore/{category}
    defaults: { _controller: CustomWebBundle:Course:explore, category:'' }

classroom_courses_pick:
    pattern: /classroom/{classroomId}/course/pick
    defaults: { _controller: CustomWebBundle:Classroom\Course:pick }

classroom_course_search:
    pattern: /classroom/{classroomId}/course/search
    defaults: { _controller: CustomWebBundle:Classroom\Course:search }


search:
    pattern:  /search
    defaults: { _controller: CustomWebBundle:Search:index }

homepage:
    pattern:  /
    defaults: { _controller: CustomWebBundle:Default:index }

homepage_recommend_courses:
    pattern:  /recommend-courses
    defaults: { _controller: CustomWebBundle:Default:recommedCourses}