admin_keyword:
    pattern:  /keyword/
    defaults: { _controller: SensitiveWordBundle:Sensitive:index }

admin_keyword_create:
    pattern:  /keyword/create
    defaults: { _controller: SensitiveWordBundle:Sensitive:create }

admin_keyword_delete:
    pattern:  /keyword/{id}/delete
    defaults: { _controller: SensitiveWordBundle:Sensitive:delete }
    methods:  [POST]

admin_keyword_change:
    pattern:  /keyword/{id}/change
    defaults: { _controller: SensitiveWordBundle:Sensitive:change }

admin_keyword_banlogs:
    pattern:  /keyword/banlogs
    defaults: { _controller: SensitiveWordBundle:Sensitive:banlogs }