importer:
  course-member: Biz\Importer\CourseMemberImporter
  classroom-member: Biz\Importer\ClassroomMemberImporter

order:
  course:
    processor: Biz\Order\OrderProcessor\CourseOrderProcessor
    order_show_template: order/order-course.html.twig
  classroom:
    processor: Biz\Order\OrderProcessor\ClassroomOrderProcessor
    order_show_template: order/classroom.html.twig
  vip:
    processor: Biz\Order\OrderProcessor\VipOrderProcessor
    order_show_template: order/vip.html.twig
  coin:
    processor: Biz\Order\OrderProcessor\CoinOrderProcessor

reward_point:
    common-acquire: Biz\RewardPoint\Processor\CommonAcquireRewardPoint
    course-acquire: Biz\RewardPoint\Processor\CourseAcquireRewardPoint
  