imports:
    - { resource: event_subscribers.yml }

services:
    extension.manager:
        class: AppBundle\Extension\ExtensionManager

    extension.default:
        class: AppBundle\Extension\DefaultExtension
        arguments: ['@biz']
        tags:
            - { name: extension }

    biz.service_provider.collector:
        class: Biz\ServiceProviderCollector

    web.twig.question_type_extension:
        class: AppBundle\Twig\QuestionTypeExtension
        arguments:    ['@service_container','@biz']
        tags:
            - { name: twig.extension }

    web.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@biz']
        tags:
            - { name: twig.extension }

    web.twig.activity_extension:
        class: AppBundle\Twig\ActivityExtension
        arguments:    ['@service_container','@biz']
        tags:
            - { name: twig.extension }

    web.twig.live_extension:
        class: AppBundle\Twig\LiveExtension
        tags:
            - { name: twig.extension }