mapi_course_pay:
    path:  /courses/{courseId}/pay
    defaults: { _controller: TopxiaMobileBundle:MobileOrder:payCourse }

mapi_course_refund:
    path:  /courses/{courseId}/refund
    defaults: { _controller: TopxiaMobileBundle:MobileOrder:refundCourse }

mapi_order_submit_pay_request:
    path:  /order/{id}/submit_pay_request
    defaults: { _controller: TopxiaMobileBundle:MobileOrder:submitPayRequest }


topxia_mobile_alipay_notify:
    path:  /{name}/alipay_notify
    defaults: { _controller: TopxiaMobileBundle:MobileAlipay:payNotify }

topxia_mobile_alipay_pay:
    path:  /alipay_pay
    defaults: { _controller: TopxiaMobileBundle:MobileAlipay:pay }

topxia_mobile_alipay_callback:
    path:  /{name}/alipay_callback
    defaults: { _controller: TopxiaMobileBundle:MobileAlipay:payCallBack }

topxia_mobile_qrcode:
    path:  /qrcode
    defaults: { _controller: TopxiaMobileBundle:Qrcode:index }

mapi_courses:
    path:  /courses
    defaults: { _controller: TopxiaMobileBundle:Course:courses }

mapi_about:
    path:  /about
    defaults: { _controller: TopxiaMobileBundle:User:getSchoolSite }

mapi_course:
    path:  /courses/{courseId}
    defaults: { _controller: TopxiaMobileBundle:Course:course }

mapi_course_items:
    path:  /courses/{courseId}/items
    defaults: { _controller: TopxiaMobileBundle:Course:items }

mapi_course_lesson:
    path:  /courses/{courseId}/lessons/{lessonId}
    defaults: { _controller: TopxiaMobileBundle:Course:lesson }

mapi_course_lesson_media:
    path:  /courses/{courseId}/lessons/{lessonId}/media
    defaults: { _controller: TopxiaMobileBundle:Course:lessonMedia }

mapi_course_reviews:
    path:  /courses/{courseId}/reviews
    defaults: { _controller: TopxiaMobileBundle:CourseReview:reviews }
    methods: [GET]

mapi_course_review_create:
    path:  /courses/{courseId}/reviews
    defaults: { _controller: TopxiaMobileBundle:CourseReview:create }
    methods: [POST]

mapi_course_review_create_html5:
    path:  /courses/{courseId}/review_create
    defaults: { _controller: TopxiaMobileBundle:CourseReview:create }

mapi_course_review_get:
    path:  /courses/{courseId}/reviews/{reviewId}
    defaults: { _controller: TopxiaMobileBundle:CourseReview:get }
    methods: [GET]

mapi_course_review_update:
    path:  /courses/{courseId}/reviews/{reviewId}
    defaults: { _controller: TopxiaMobileBundle:CourseReview:update }
    methods: [POST]

mapi_course_review_update_html5:
    path:  /courses/{courseId}/reviews/{reviewId}/update
    defaults: { _controller: TopxiaMobileBundle:CourseReview:update }

mapi_course_favorite:
    path:  /courses/{courseId}/favorite
    defaults: { _controller: TopxiaMobileBundle:Course:favorite }
    methods: [GET, POST]

mapi_course_unfavorite:
    path:  /courses/{courseId}/unfavorite
    defaults: { _controller: TopxiaMobileBundle:Course:unfavorite }
    methods: [GET, POST]

mapi_course_can_learn:
    path:  /courses/{courseId}/can_learn
    defaults: { _controller: TopxiaMobileBundle:Course:canLearn }
    methods: [GET, POST]

mapi_course_lesson_learn:
    path:  /courses/{courseId}/lessons/{lessonId}/learn
    defaults: { _controller: TopxiaMobileBundle:Course:learn }
    methods: [GET, POST]

mapi_course_lesson_unlearn:
    path:  /courses/{courseId}/lessons/{lessonId}/unlearn
    defaults: { _controller: TopxiaMobileBundle:Course:unLearn }
    methods: [GET, POST]

mapi_course_lesson_learn_status:
    path:  /courses/{courseId}/lessons/{lessonId}/learn_status
    defaults: { _controller: TopxiaMobileBundle:Course:learnStatus }

mapi_me_favorite_courses:
    path:  /me/favorite_courses
    defaults: { _controller: TopxiaMobileBundle:Course:meFavorites }

mapi_me_learning_courses:
    path:  /me/learning_courses
    defaults: { _controller: TopxiaMobileBundle:Course:meLearnings }

mapi_me_learned_courses:
    path:  /me/learned_courses
    defaults: { _controller: TopxiaMobileBundle:Course:meLearneds }

mapi_me_notifications:
    path:  /me/notifications
    defaults: { _controller: TopxiaMobileBundle:User:notifiactions }

mapi_user:
    path:  /users/{id}
    defaults: { _controller: TopxiaMobileBundle:User:user }

mapi_user_register:
    path:  /users
    defaults: { _controller: TopxiaMobileBundle:User:register }
    methods: [POST]

mapi_user_register_html5:
    path:  /user_register
    defaults: { _controller: TopxiaMobileBundle:User:register }

mapi_user_login:
    path:  /login
    defaults: { _controller: TopxiaMobileBundle:User:login }

mapi_user_logout:
    path:  /logout
    defaults: { _controller: TopxiaMobileBundle:User:logout }

mapi_user_login_with_token:
    path:  /login_with_token
    defaults: { _controller: TopxiaMobileBundle:User:loginWithToken }

mapi_user_login_with_site:
    path:  /login_with_site
    defaults: { _controller: TopxiaMobileBundle:User:loginWithSite }

mapi_mobile_version:
    path:  /mobile_version
    defaults: { _controller: TopxiaMobileBundle:Mobile:mobileVersion }

mapi_mobile_notify_version:
    path:  /notify_mobile_version
    defaults: { _controller: TopxiaMobileBundle:Mobile:notifyMobileVersion }

mapi_mobile_regist_device:
    path:  /regist_device
    defaults: { _controller: TopxiaMobileBundle:Mobile:mobileDeviceRegist }
    methods: [POST, GET]

mapi_mobile_log:
    path:  /mobile_school_login
    defaults: { _controller: TopxiaMobileBundle:Mobile:mobileSchoolLogin }
    methods: [POST, GET]