course_manage_course_set:
  path: /course_set/{courseId}/courses
  defaults: {_controller:WebBundle:TaskManage:courseSet}

course_manage_tasks:
  path:  /course/{courseId}/manage/tasks
  defaults: { _controller: WebBundle:CourseManage:tasks }

course_manage_items_sort:
  path:  /course/{courseId}/manage/items/sort
  defaults: { _controller: WebBundle:CourseManage:courseItemsSort }
  methods: ['POST']

course_manage_chapter_create:
    path:  /course/{id}/manage/chapter/create
    defaults: { _controller: WebBundle:CourseChapterManage:create }

course_manage_chapter_edit:
    path:  /course/{courseId}/manage/chapter/{chapterId}/edit
    defaults: { _controller: WebBundle:CourseChapterManage:edit }

course_manage_chapter_delete:
    path:  /course/{courseId}/manage/chapter/{chapterId}/delete
    defaults: { _controller: WebBundle:CourseChapterManage:delete }
    methods: [POST]

course_manage_task_create:
  path:  /course/{courseId}/task
  defaults: { _controller: WebBundle:TaskManage:create}

course_manage_task_fields:
  path:  /course/{courseId}/task_fields/{mode}
  defaults: { _controller: WebBundle:TaskManage:taskFields }

course_manage_task_update:
  path:  /course/{courseId}/task/{id}/update
  defaults: { _controller: WebBundle:TaskManage:update }

course_manage_task_delete:
  path:  /course/{courseId}/task/{id}/delete
  defaults: { _controller: WebBundle:TaskManage:delete }

course_task_show:
  path:  /course/{courseId}/task/{id}/show
  defaults: { _controller: WebBundle:Task:show }

course_task_activity_show:
  path:  /course/{courseId}/task/{id}/activity_show
  defaults: { _controller: WebBundle:Task:taskActivity }

task_live_entry:
  path: /course/{courseId}/activity/{id}/live_entry
  defaults: {_controller: WebBundle:LiveActivity:liveEntry}

course_activity_trigger:
  path: /course/{courseId}/activity/{activityId}/trigger
  defaults: { _controller: WebBundle:Activity:trigger }
  methods: [POST]

media_materiallib_choose:
    path: /media/materiallib/choose
    defaults: { _controller: WebBundle:FileChooser:materialChoose }

media_materiallib_contacts:
    path: /media/materiallib/contacts
    defaults: { _controller: WebBundle:FileChooser:findMySharingContacts }

media_course_file_choose:
    path: /media/corusefile/{courseId}/choose
    defaults: { _controller: WebBundle:FileChooser:courseFileChoose }

media_video_import:
    path: /media/course/{courseId}/import
    defaults: { _controller: WebBundle:FileChooser:import }

uploader_auth_v2:
    path:  /uploader/v2/auth
    defaults: { _controller: WebBundle:Uploader:auth }
    methods: [GET]

uploader_init_v2:
  path:  /uploader/v2/init
  defaults: { _controller: WebBundle:Uploader:init }
  methods: [GET]

uploader_finished_v2:
  path:  /uploader/v2/finished
  defaults: { _controller: WebBundle:Uploader:finished }
  methods: [GET]

#testpaper
course_manage_testpaper:
  path: /testpaper2/course/{courseId}/manage/testpaper
  defaults: { _controller: WebBundle:TestpaperManage:index }

course_manage_testpaper_create:
  path: /testpaper2/course/{courseId}/manage/testpaper/create
  defaults: { _controller: WebBundle:TestpaperManage:create }

course_manage_testpaper_questions:
  path: /testpaper2/course/{courseId}/manage/testpaper/{testpaperId}/items
  defaults: { _controller: WebBundle:TestpaperManage:questions }

course_manage_testpaper_items_get:
  path: /testpaper2/course/{courseId}/manage/testpaper/items/get
  defaults: { _controller: WebBundle:TestpaperManage:itemsGet }

testpaper_do:
  path: /lesson/{lessonId}/testpaper/{testId}/do
  defaults: { _controller: WebBundle:Testpaper:doTestpaper }

testpaper_show:
  path: /testpaper/{testId}/show
  defaults: { _controller: WebBundle:Testpaper:showTest }

testpaper_result_show:
  path: /testpaper/result/{resultId}/show
  defaults: { _controller: WebBundle:Testpaper:showResult }

testpaper_result_submit:
  path: /testpaper/result/{resultId}/submit
  defaults: { _controller: WebBundle:Testpaper:submitTest }

testpaper_finish_test:
  path: /testpaper/result/{resultId}/finish
  defaults: { _controller: WebBundle:Testpaper:finishTest }


#homework
course_manage_homework:
  path: /course/{courseId}/manage/homework
  defaults: { _controller: WebBundle:HomeworkManage:index }

course_manage_homework_create:
  path: /course/{courseId}/manage/lesson/{lessonId}/homework/create
  defaults: { _controller: WebBundle:HomeworkManage:create }


course_manage_homework_question_picked:
  path: /course/{courseId}/manage/question/picked
  defaults: { _controller: WebBundle:HomeworkManage:questionPicked }


#exercise
course_manage_exercise_create:
  path: /course/{courseId}/manage/lesson/{lessonId}/exercise/create
  defaults: { _controller: WebBundle:ExerciseManage:create }

#todo 与homework_check合并
course_manage_exercise_check:
  path:  /course/{courseId}/manage/exercise/check
  defaults: { _controller: WebBundle:ExerciseManage:buildCheck }

#question
course_manage_question_picker:
  path: /course/{courseId}/manage/question/picker
  defaults: { _controller: WebBundle:QuestionManage:questionPicker }

course_manage_question_picked:
  path:  /course/{courseId}/manage/question/{questionId}/picked
  defaults: { _controller: WebBundle:QuestionManage:PickedQuestion }

